# Generated by Django 2.2.24 on 2021-10-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapTableOfContents',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_bootstrap_toc_bootstraptableofcontents', serialize=False, to='cms.CMSPlugin')),
                ('scope_filter_elements', models.CharField(blank=True, default='main', help_text='Filter heading elements within selected tags only, .e.g $("main h1, main h2")', max_length=250, null=True, verbose_name='Elements Within Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
